services:
  react-app:
    build: ./frontend/
    ports:
      - "4000:80"
    networks:
      - react-flask
    depends_on:
      - backend

  backend:
    build: ./backend/
    command: sh -c "sleep 10s ; python3 src"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - react-flask
      - flask-mysql

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: "pager_duty"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3301:3306"
    networks:
      - flask-mysql

networks:
  react-flask: {}
  flask-mysql: {}
