services:
  python-app:
    build: ./flask-app/
    command: sh -c "sleep 10s ; python3 src"
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: "pager_duty"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
